version: '3.8'
services:
  es-api:
    image: jpmadrigal/mrrcrm-api-dev:latest
    container_name: mrrcrm-api-dev
    restart: unless-stopped
    env_file:
      - ../../.env.development
    ports:
      - 9000:9000