version: '3.8'
services:
  mrrcrm-api:
    image: jpmadrigal/mrrcrm-api-dev-arm:latest
    container_name: mrrcrm-api-dev-arm
    restart: unless-stopped
    env_file:
      - ../../.env.development
    ports:
      - 9000:9000
    volumes:
      - ../../../uploads:/usr/src/app/apps/api/build/uploads