import QueryWrapper from "@/components/query-wrapper";
import CampaignCheckerWrapper from "@/components/campaign-checker-wrapper";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MRR - CRM",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryWrapper>
          <CampaignCheckerWrapper>
            {children}
          </CampaignCheckerWrapper>
        </QueryWrapper>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
