version: '3.8'
services:
  es-web:
    image: jpmadrigal/mrrcrm-web-dev:latest
    build:
      context: ../../
      dockerfile: ./docker/web/Dockerfile
      args:
        API_URL: ${API_URL}
        WEB_URL: ${WEB_URL}
